version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: frontend-new/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://api:5000

  api:
    build:
      context: .
      dockerfile: packages/api/Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/investment_db
      - JWT_SECRET=your-production-secret
      - ALPHA_VANTAGE_API_KEY=${ALPHA_VANTAGE_API_KEY}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=investment_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 